version: '3'

services:
  app:
    container_name: codeigniter3-starter
    image: codeigniter3-starter
    build:
      context: .
      dockerfile: docker/Dockerfile80
    ports:
      - 8080:80
    volumes:
      - .:/app
      - /app/vendor